# Exported from Render on 2026-03-13T07:46:14Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: niravpanchal11
      runtime: docker
      repo: https://github.com/niravpanchal11/niravpanchal11
      plan: free
      envVars:
      - key: RECIPIENT_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
      - key: SENDER_EMAIL
        sync: false
      region: ohio
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
